# Generated by Django 3.0.4 on 2020-03-16 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_is', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_data', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 16, 1, 16, 7, 580536))),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
