# Generated by Django 3.0.4 on 2020-03-16 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_data',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 16, 1, 27, 40, 408598)),
        ),
    ]
