# Generated by Django 3.0.4 on 2020-03-16 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200316_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 16, 3, 15, 0, 662451, tzinfo=utc)),
        ),
    ]
